import Head from "next/head";
import { useForm } from "react-hook-form";
import axios from "axios";
import { useState } from "react";
import { useRouter } from "next/router";
import Link from "next/link";
import { Title } from "../components/Title";

const Login = () => {
  const [email_address, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const router = useRouter();
  const [error, setError] = useState("");

  const loginItems = [
    {
      label: "メールアドレス",
      name: "email_address",
      rules: {
        required: "入力が必須の項目です。",
        pattern: {
          value: /^[\w\-._]+@[\w\-._]+\.[A-Za-z]+/,
          message: "正しいメールアドレス形式を入力してください。",
        },
      },
    },
    {
      label: "パスワード",
      name: "password",
      rules: {
        required: "入力が必須の項目です。",
        minLength: {
          value: 8,
          message: "8文字以上入力してください。",
        },
      },
    },
  ];
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm();

  const fetchData = async (data) => {
    try {
      const response = await axios.post("http://localhost:80/api/login", data);
      localStorage.setItem("auth_token", response.data.token);
      localStorage.setItem("auth_name", response.data.user);
      router.push("/");
      console.log("Registration successful!", response.data);
    } catch (error) {
      setError("メールアドレス、もしくはパスワードが間違っています。");
      console.error("Registration failed:", error);
    }
  };

  return (
    <div className="">
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-row min-h-screen">
        <Title info={{ title: "LOGIN", subtitle: "管理者ログイン" }} />
        <div className="bg-gray-200 w-2/3 px-20 pt-40">
          <div className="text-center">
            <p className="font-bold text-xl">アカウントをお持ちの方はこちら</p>
          </div>
          <form onSubmit={handleSubmit(fetchData)} className="px-20 py-10">
            {loginItems.map(({ label, name, rules }) => (
              <div key={name} className="mb-5">
                <label className="font-bold">{label}</label>
                <input
                  className="mt-4 block w-full p-2 rounded-lg hover:outline-green-400"
                  type={name.includes("password") ? "password" : "text"}
                  {...register(name, rules)}
                />
                {errors[name] && (
                  <div className="text-red-500 text-lg font-semibold">
                    {errors[name]?.message}
                  </div>
                )}
              </div>
            ))}
            {error && (
              <div className="text-red-500 text-lg font-semibold">{error}</div>
            )}
            <div className="text-center font-bold">
              <button
                type="submit"
                className="bg-green-400 text-lg rounded-3xl text-white px-4 py-2 my-10 w-2/3 shadow-lg"
              >
                ログイン
              </button>
              <p className="text-green-300">パスワードを忘れた方はこちら</p>
              <div className="py-10 mt-10 border-t-4 border-gray-300">
                <p className="text-xl pb-10">
                  アカウントをお持ちでない方はこちら
                </p>

                <Link href="/signup">
                  <a className="text-lg rounded-3xl bg-white text-green-400 px-40 py-2 my-10 w-2/3 shadow-lg ring-2 ring-green-400">
                    新規登録
                  </a>
                </Link>
              </div>
            </div>
          </form>
        </div>
      </main>
    </div>
  );
};

export default Login;
