import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Footer  from "../components/Footer"

const Login: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form action="">
            <div>
                <p>メールアドレス</p>
                <input type="text" />
            </div>
            <div>
                <p>パスワード</p>
                <input type="password" />
            </div>
            <button type="submit" >ログインする</button>
        </form>
      </main>

      <Footer />
    </div>
  )
}

export default Login
