import Head from "next/head";
import styles from "../styles/Home.module.css";
import Footer from "../components/Footer";
import { useForm } from "react-hook-form";
import axios from "axios";
import { useState } from "react";

const Login = () => {
  const [email_address, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm();

  const fetchData = async () => {
    try {
      const formData = {
        email_address,
        password,
      };

      const response = await axios.post(
        "https://jsonplaceholder.typicode.com/posts/",
        formData
      );
      console.log("Registration successful!", response.data);
    } catch (error) {
      console.error("Registration failed:", error);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form onSubmit={handleSubmit(fetchData)}>
          <div>
            <p>メールアドレス</p>
            <input
              type="email"
              value={email_address}
              {...register("email_address", {
                required: "入力が必須の項目です。",
              })}
              onChange={(e) => setEmail(e.target.value)}
            />
            {errors.email_address && (
              <div className={styles.errors}>入力が必須の項目です。</div>
            )}
          </div>
          <div>
            <p>パスワード</p>
            <input
              type="password"
              value={password}
              {...register("password", {
                required: "入力が必須の項目です。",
              })}
              onChange={(e) => setPassword(e.target.value)}
            />
            {errors.password && (
              <div className={styles.errors}>入力が必須の項目です。</div>
            )}
          </div>
          <button type="submit">ログインする</button>
        </form>
      </main>

      <Footer />
    </div>
  );
};

export default Login;
