import type { NextPage } from 'next'
import Head from 'next/head'
import styles from './signup.module.css'
import { useState } from 'react';
import { useRouter } from 'next/router';
import axios from 'axios';

const baseURL = "https://jsonplaceholder.typicode.com/posts/"

const Signup: NextPage = () => {
    const router = useRouter();
    const [register_id, setId] = useState('');
    const [name, setName] = useState('');
    const [name_kana, setNamekana] = useState('');
    const [phone_number, setPhonenumber] = useState('');
    const [email_address, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [password_confirmation, setPasswordConfirm] = useState('');

    const fetchData = async () => {
        try {
            const formData = {
                register_id,
                name,
                name_kana,
                phone_number,
                email_address,
                password,
                password_confirmation,
            };

            const response = await axios.post("https://jsonplaceholder.typicode.com/posts/", formData);

            console.log('Registration successful!', response.data);
        } catch (error) {
            console.error('Registration failed:', error);
        }
    };

    const handleRegister = () => {
        fetchData();
        router.push('/login');
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>C-Signup</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div className={styles.title}>
                    <div className={styles.a}>
                        <h2>SIGN UP</h2>
                    </div>
                    <div className={styles.b}>
                        <p>管理者者情報登録</p>
                    </div>
                </div>
                <div className={styles.form}>
                    <div className={styles.formtitle}>
                        <p>管理者情報</p>
                    </div>
                    <form action="">
                        <div className={styles.formData}>
                            <div>
                                <p>管理企業ID</p>
                                <input
                                type="text"
                                value={register_id}
                                onChange={(e) => setId(e.target.value)}
                                />
                            </div>
                            <div>
                                <p>氏名</p>
                                <input
                                type="text"
                                value={name}
                                onChange={(e) => setName(e.target.value)}
                                />
                            </div>
                            <div>
                                <p>氏名(カナ)</p>
                                <input
                                type="text"
                                value={name_kana}
                                onChange={(e) => setNamekana(e.target.value)}
                                />
                            </div>
                            <div>
                                <p>携帯電話番号</p>
                                <input
                                type="text"
                                value={phone_number}
                                onChange={(e) => setPhonenumber(e.target.value)}
                                />
                            </div>
                            <div>
                                <p>メールアドレス</p>
                                <input
                                type="email"
                                value={email_address}
                                onChange={(e) => setEmail(e.target.value)}
                                />
                            </div>
                            <div>
                                <p>パスワード[半角英数字の組み合わせ8桁以上]</p>
                                <input
                                type="password"
                                value={password}
                                onChange={(e) => setPassword(e.target.value)}
                                />
                            </div>
                            <div>
                                <p>パスワード[確認]</p>
                                <div>
                                <input
                                type="password"
                                value={password_confirmation}
                                onChange={(e) => setPasswordConfirm(e.target.value)}
                                />
                            </div>
                            </div>
                        </div>
                        <div>
                            <button type="button" onClick={handleRegister} className={styles.button}>
                                登録する
                            </button>
                        </div>
                    </form>
                </div>
            </main>
        </div>
    )
}

export default Signup