import type { NextPage } from 'next'
import Head from 'next/head'
import styles from './signup.module.css'
import { useState } from 'react';
import { useRouter } from 'next/router';
import axios from 'axios';

const baseURL = "https://localhost:80";

const Signup: NextPage = () => {
    const router = useRouter();
    const [id, setId] = useState('');
    const [name, setName] = useState('');
    const [name_kana, setNamekana] = useState('');
    const [phonenumber, setPhonenumber] = useState('');
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [password_confirm, setPasswordConfirm] = useState('');
    const [register_code, setRegisterCode] = useState('');

    const fetchData = async () => {
        try {
            const formData = {
                id,
                name,
                name_kana,
                phonenumber,
                email,
                password,
                password_confirm,
                register_code,
            };

            const response = await axios.post("http://localhost:3000/signup", formData);

            console.log('Registration successful!', response.data);
            localStorage.setItem('nickname', JSON.stringify(email));
        } catch (error) {
            console.error('Registration failed:', error);
        }
    };

    const handleRegister = () => {
        fetchData();
        router.push('/login');
    }

  return (
    <div className={styles.container}>
      <Head>
        <title>C-Signup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.title}>
            <div className={styles.a}>
                <h2>SIGN UP</h2>
            </div>
            <div className={styles.b}>
                <p>管理者者情報登録</p>
            </div>
        </div>
        <div className={styles.form}>
            <div className={styles.formtitle}>
                <p>管理者情報</p>
            </div>
            <form action="">
                <div className={styles.formData}>
                    <div>
                        <p>管理企業ID</p>
                        <input
                        type="text"
                        value={id}
                        onChange={(e) => setId(e.target.value)}
                        />
                    </div>
                    <div>
                        <p>氏名</p>
                        <input
                        type="text"
                        value={name}
                        onChange={(e) => setName(e.target.value)}
                        />
                    </div>
                    <div>
                        <p>氏名(カナ)</p>
                        <input
                        type="text"
                        value={name_kana}
                        onChange={(e) => setNamekana(e.target.value)}
                        />
                    </div>
                    <div>
                        <p>携帯電話番号</p>
                        <input
                        type="text"
                        value={phonenumber}
                        onChange={(e) => setPhonenumber(e.target.value)}
                        />
                    </div>
                    <div>
                        <p>メールアドレス</p>
                        <input
                        type="email"
                        value={email}
                        onChange={(e) => setEmail(e.target.value)}
                        />
                    </div>
                    <div>
                        <p>パスワード[半角英数字の組み合わせ8桁以上]</p>
                        <input
                        type="password"
                        value={password}
                        onChange={(e) => setPassword(e.target.value)}
                        />
                    </div>
                    <div>
                        <p>パスワード[確認]</p>
                        <div>
                        <input
                        type="password"
                        value={password_confirm}
                        onChange={(e) => setPasswordConfirm(e.target.value)}
                        />
                    </div>
                    </div>
                    <div>
                        <p>登録用コード</p>
                        <input
                        type="text"
                        value={register_code}
                        onChange={(e) => setRegisterCode(e.target.value)}
                        />
                    </div>
                </div>
                <div>
                    <button type="button" onClick={handleRegister} className={styles.button}>
                        登録する
                    </button>
                </div>
            </form>
        </div>
      </main>
    </div>
  )
}

export default Signup